version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/prod/django/Dockerfile
    image: trade_harbor_web
    # '/start' is the shell script used to run the service
    command: /start.sh
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
#      - .:/app
      - static_volume:/app/static/
      - media_volume:/app/media/
    expose:
      - 8000
    # env_file is used to manage the env variables of our project
    env_file:
      - ./.env
    depends_on:
      - redis
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  redis:
    image: redis:7-alpine

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/prod/django/Dockerfile
    image: trade_harbor_celery_worker
    command: /start-celeryworker.sh
#    volumes:
#      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/prod/django/Dockerfile
    image: trade_harbor_celery_beat
    command: /start-celerybeat.sh
#    volumes:
#      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - db

  nginx:
    build: ./compose/prod/nginx
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media


#  flower:
#    build:
#      context: .
#      dockerfile: ./compose/prod/django/Dockerfile
#    image: trade_harbor_flower
#    command: /start-flower.sh
#    volumes:
#      - .:/app
#    env_file:
#      - ./.env
#    ports:
#      - 5557:5555
#    depends_on:
#      - redis
#      - db

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/postgres_data
      o: bind
  static_volume:
  media_volume:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/media
      o: bind