# Generated by Django 5.0.1 on 2024-01-31 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliercategory',
            name='parent_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supplier_categories', to='supplies.suppliercategory'),
        ),
    ]
