# Generated by Django 5.0.1 on 2024-01-31 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_alter_suppliercategory_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='supplies.sitecategory'),
        ),
    ]
