# Generated by Django 5.0.1 on 2024-02-01 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0004_alter_suppliercategory_parent_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplieroffer',
            name='categoryId',
        ),
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='supplies.sitecategory'),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='category',
            field=models.ForeignKey(db_column='categoryId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='supplies.suppliercategory'),
        ),
    ]
