# Generated by Django 5.0.1 on 2024-02-01 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0005_remove_supplieroffer_categoryid_offer_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplieroffer',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='supplies.suppliercategory'),
        ),
    ]
