# Generated by Django 5.0.1 on 2024-02-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0006_alter_supplieroffer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
