# Generated by Django 5.0.1 on 2024-02-15 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0007_alter_offer_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='supplies.sitecategory'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description_ua',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='group_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='keywords',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='keywords_ua',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='name_ua',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='params',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pictures',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
