# Generated by Django 5.0.1 on 2024-02-16 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0008_alter_offer_category_alter_offer_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='supplies.sitecategory'),
        ),
        migrations.AlterField(
            model_name='suppliercategory',
            name='parent_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='supplies.suppliercategory'),
        ),
    ]
