# Generated by Django 5.0.1 on 2024-02-18 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0009_alter_sitecategory_parent_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplieroffer',
            name='article',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='barcode',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='supplies.suppliercategory'),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='gtin',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='minimum_order_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='mpn',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='quantity_in_stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='stock_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='vendor',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
