# Generated by Django 5.0.1 on 2024-02-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0010_alter_supplieroffer_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplieroffer',
            name='group_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
