# Generated by Django 5.0.1 on 2024-03-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0011_alter_supplieroffer_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='price_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
