# Generated by Django 5.0.1 on 2024-05-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0012_offer_price_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='suggested_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
